import {
  TrendingUp, Star, BarChart2, PieChart, Users,
  Newspaper, ArrowUpDown, DollarSign, Gauge,
  Activity, Flame,
} from 'lucide-react';
import type { WidgetDefinition } from '../types/widgets.types';

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  {
    type: 'kpi_portfolio',
    title: 'KPI Портфеля',
    description: 'Суммарная стоимость и изменение',
    icon: TrendingUp,
    color: '#e11d48',
    availableSizes: [
      { w: 4, h: 1, label: '4×1' },
      { w: 3, h: 1, label: '3×1' },
      { w: 2, h: 1, label: '2×1' },
    ],
    defaultSize: { w: 4, h: 1, label: '4×1' },
    minW: 2, minH: 1, maxW: 4, maxH: 2,
  },
  {
    type: 'watchlist',
    title: 'Вотч-лист',
    description: 'Отслеживаемые активы',
    icon: Star,
    color: '#f59e0b',
    availableSizes: [
      { w: 2, h: 2, label: '2×2' },
      { w: 2, h: 3, label: '2×3' },
      { w: 3, h: 2, label: '3×2' },
    ],
    defaultSize: { w: 2, h: 2, label: '2×2' },
    minW: 2, minH: 2, maxW: 3, maxH: 4,
  },
  {
    type: 'price_chart',
    title: 'График цены',
    description: 'Динамика актива',
    icon: BarChart2,
    color: '#3b82f6',
    availableSizes: [
      { w: 2, h: 2, label: '2×2' },
      { w: 3, h: 2, label: '3×2' },
      { w: 4, h: 2, label: '4×2' },
    ],
    defaultSize: { w: 3, h: 2, label: '3×2' },
    minW: 2, minH: 2, maxW: 4, maxH: 3,
  },
  {
    type: 'allocation',
    title: 'Распределение',
    description: 'Доли портфеля по активам',
    icon: PieChart,
    color: '#8b5cf6',
    availableSizes: [
      { w: 1, h: 2, label: '1×2' },
      { w: 2, h: 2, label: '2×2' },
    ],
    defaultSize: { w: 2, h: 2, label: '2×2' },
    minW: 1, minH: 2, maxW: 2, maxH: 3,
  },
  {
    type: 'community',
    title: 'Сообщество',
    description: 'Посты трейдеров',
    icon: Users,
    color: '#06b6d4',
    availableSizes: [
      { w: 2, h: 2, label: '2×2' },
      { w: 2, h: 3, label: '2×3' },
    ],
    defaultSize: { w: 2, h: 2, label: '2×2' },
    minW: 2, minH: 2, maxW: 3, maxH: 4,
  },
  {
    type: 'news',
    title: 'Новости рынка',
    description: 'Лента финансовых новостей',
    icon: Newspaper,
    color: '#64748b',
    availableSizes: [
      { w: 2, h: 2, label: '2×2' },
      { w: 3, h: 2, label: '3×2' },
    ],
    defaultSize: { w: 2, h: 2, label: '2×2' },
    minW: 2, minH: 2, maxW: 3, maxH: 4,
  },
  {
    type: 'top_movers',
    title: 'Топ движения',
    description: 'Лидеры роста и падения',
    icon: ArrowUpDown,
    color: '#22c55e',
    availableSizes: [
      { w: 2, h: 2, label: '2×2' },
      { w: 2, h: 3, label: '2×3' },
    ],
    defaultSize: { w: 2, h: 2, label: '2×2' },
    minW: 2, minH: 2, maxW: 3, maxH: 3,
  },
  {
    type: 'forex_rates',
    title: 'Форекс курсы',
    description: 'Основные валютные пары',
    icon: DollarSign,
    color: '#0ea5e9',
    availableSizes: [
      { w: 2, h: 2, label: '2×2' },
      { w: 3, h: 1, label: '3×1' },
    ],
    defaultSize: { w: 2, h: 2, label: '2×2' },
    minW: 2, minH: 1, maxW: 3, maxH: 3,
  },
  {
    type: 'fear_greed',
    title: 'Страх и жадность',
    description: 'Индекс настроения рынка',
    icon: Gauge,
    color: '#f97316',
    availableSizes: [
      { w: 1, h: 1, label: '1×1' },
      { w: 1, h: 2, label: '1×2' },
      { w: 2, h: 1, label: '2×1' },
    ],
    defaultSize: { w: 1, h: 2, label: '1×2' },
    minW: 1, minH: 1, maxW: 2, maxH: 2,
  },
  {
    type: 'market_volume',
    title: 'Объём рынка',
    description: 'Общий торговый объём 24ч',
    icon: Activity,
    color: '#a855f7',
    availableSizes: [
      { w: 2, h: 1, label: '2×1' },
      { w: 3, h: 1, label: '3×1' },
    ],
    defaultSize: { w: 2, h: 1, label: '2×1' },
    minW: 2, minH: 1, maxW: 4, maxH: 2,
  },
  {
    type: 'trending_coins',
    title: 'Трендовые монеты',
    description: 'Топ по объёму торгов',
    icon: Flame,
    color: '#ef4444',
    availableSizes: [
      { w: 2, h: 2, label: '2×2' },
      { w: 3, h: 2, label: '3×2' },
    ],
    defaultSize: { w: 2, h: 2, label: '2×2' },
    minW: 2, minH: 2, maxW: 3, maxH: 3,
  },
];